/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PrincipalGUI;

import GUI.ComprasGUI;
import GUIvendedor.BoletaDeReparaciones;
import GUIvendedor.BoletaDeVenta;
import GUIvendedor.CajaGUI;
import GUIvendedor.productosG;
import ReportesPack.iReportes;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author WANOSOFT
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        
        try {
			  UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			} catch(Exception e) {
			  System.out.println("Error setting native LAF: " + e);
			}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new org.edisoncor.gui.button.ButtonTask();
        jPanel3 = new javax.swing.JPanel();
        btnVender = new org.edisoncor.gui.button.ButtonTask();
        btnCaja = new org.edisoncor.gui.button.ButtonTask();
        btnComprar = new org.edisoncor.gui.button.ButtonTask();
        btnReportes = new org.edisoncor.gui.button.ButtonTask();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mniProductos = new javax.swing.JMenuItem();
        nmiCaja = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGenerar = new javax.swing.JMenu();
        mniVentas = new javax.swing.JMenuItem();
        mniReparaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atraz.png"))); // NOI18N
        btnSalir.setText("Cerrar Sesión");
        btnSalir.setActionCommand("Cerrar Sesión");
        btnSalir.setCategoryFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSalir.setCategorySmallFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSalir.setColorDeBorde(new java.awt.Color(0, 0, 0));
        btnSalir.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        btnSalir.setDefaultCapable(false);
        btnSalir.setDescription(" ");
        btnSalir.setFocusable(false);
        btnSalir.setRequestFocusEnabled(false);
        btnSalir.setRolloverEnabled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 150, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setOpaque(false);

        btnVender.setBackground(new java.awt.Color(102, 102, 102));
        btnVender.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addRCompra.png"))); // NOI18N
        btnVender.setText("Vender");
        btnVender.setBorderPainted(false);
        btnVender.setCategoryFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnVender.setColorDeBorde(new java.awt.Color(153, 153, 153));
        btnVender.setDescription(" ");
        btnVender.setFocusable(false);
        btnVender.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnVender.setRequestFocusEnabled(false);
        btnVender.setRolloverEnabled(false);
        btnVender.setSelected(true);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/caja.png"))); // NOI18N
        btnCaja.setText("Caja");
        btnCaja.setBorderPainted(false);
        btnCaja.setCategoryFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnCaja.setDefaultCapable(false);
        btnCaja.setDescription(" ");
        btnCaja.setFocusable(false);
        btnCaja.setRequestFocusEnabled(false);
        btnCaja.setRolloverEnabled(false);
        btnCaja.setVerifyInputWhenFocusTarget(false);
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(204, 204, 255));
        btnComprar.setBorder(null);
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/images.png"))); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.setBorderPainted(false);
        btnComprar.setCategoryFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnComprar.setColorDeBorde(new java.awt.Color(204, 204, 255));
        btnComprar.setDefaultCapable(false);
        btnComprar.setDescription(" ");
        btnComprar.setFocusable(false);
        btnComprar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnComprar.setRequestFocusEnabled(false);
        btnComprar.setRolloverEnabled(false);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(204, 204, 255));
        btnReportes.setBorder(null);
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reportes.png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setCategoryFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnReportes.setColorDeBorde(new java.awt.Color(204, 204, 255));
        btnReportes.setDefaultCapable(false);
        btnReportes.setDescription(" ");
        btnReportes.setFocusable(false);
        btnReportes.setRequestFocusEnabled(false);
        btnReportes.setRolloverEnabled(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 260));

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("PAPSIS 1.0.0                                                  autor: WANOSOFT                      Es'7");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 400, -1));
        jLabel2.getAccessibleContext().setAccessibleName("PAPSIS 1.0.1");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 560, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 250));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        mnArchivo.setText("Archivo");

        mniProductos.setText("productos");
        mniProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProductosActionPerformed(evt);
            }
        });
        mnArchivo.add(mniProductos);

        nmiCaja.setText("caja");
        nmiCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmiCajaActionPerformed(evt);
            }
        });
        mnArchivo.add(nmiCaja);

        jMenuBar1.add(mnArchivo);

        jMenu2.setText(" Factura");

        mnuGenerar.setText("Generar");

        mniVentas.setText("ventas");
        mniVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentasActionPerformed(evt);
            }
        });
        mnuGenerar.add(mniVentas);

        mniReparaciones.setText("reparaciones");
        mniReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReparacionesActionPerformed(evt);
            }
        });
        mnuGenerar.add(mniReparaciones);

        jMenu2.add(mnuGenerar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProductosActionPerformed
        new productosG(this, true).setVisible(true);
    }//GEN-LAST:event_mniProductosActionPerformed

    private void nmiCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmiCajaActionPerformed
        new CajaGUI(this, true).setVisible(true);
    }//GEN-LAST:event_nmiCajaActionPerformed

    private void mniVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentasActionPerformed
        new BoletaDeVenta(this, true).setVisible(true);
    }//GEN-LAST:event_mniVentasActionPerformed

    private void mniReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReparacionesActionPerformed
        new BoletaDeReparaciones(this, true).setVisible(true);
    }//GEN-LAST:event_mniReparacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Logeo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        new iReportes().setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        new ComprasGUI(this, true).setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        new CajaGUI(this, true).setVisible(true);
    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed

        new BoletaDeVenta(this, true).setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btnCaja;
    private org.edisoncor.gui.button.ButtonTask btnComprar;
    private org.edisoncor.gui.button.ButtonTask btnReportes;
    private org.edisoncor.gui.button.ButtonTask btnSalir;
    private org.edisoncor.gui.button.ButtonTask btnVender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenuItem mniProductos;
    private javax.swing.JMenuItem mniReparaciones;
    private javax.swing.JMenuItem mniVentas;
    private javax.swing.JMenu mnuGenerar;
    private javax.swing.JMenuItem nmiCaja;
    // End of variables declaration//GEN-END:variables
}
